// src/app/(admin)/hq/users/page.tsx
"use client";

import { ListResponse } from "@/common/interface/ListResponse";
import { Optional } from "@/common/interface/Optional";
import { ResponseMetadata } from "@/common/interface/ResponseMetadata";
import { OptionalToastContent } from "@/common/interface/ToastContent";
import { User } from "@/common/interface/User";
import ExportDialog from "@/components/ExportDialog";
import Spinner from "@/components/Spinner";
import Toast from "@/components/Toast";
import UserStatusBadge from "@/components/UserStatusBadge";
import Link from "next/link";
import { SyntheticEvent, useEffect, useRef, useState, type JSX } from "react";

export default function UserListView(): JSX.Element {
    const [loading, setLoading] = useState<boolean>(false);
    const [query, setQuery] = useState<string>("");
    const [users, setUsers] = useState<User[]>([]);
    const [meta, setMeta] = useState<Optional<ResponseMetadata>>({});

    const [exportOpen, setExportOpen] = useState<boolean>(false);
    const [toast, setToast] = useState<OptionalToastContent>({});

    const checkboxRef = useRef<HTMLInputElement>(null);

    const fetchUsers = () => {
        setLoading(true);
        if (users.length) setUsers([]);
        fetch("/api/hq/users")
            .then(response => response.json())
            .then((payload) => {
                if (payload.error) {
                    throw new Error(payload.error);
                }
                setUsers(payload.data);
                setMeta(payload.meta ?? {});
            })
            .catch(error => setToast({ title: "Error", message: error.message || String(error) }))
            .finally(() => setTimeout(() => setLoading(false), 500));
    }

    const closeDropdown = (event: SyntheticEvent) => {
        event.stopPropagation();
        if (checkboxRef.current) checkboxRef.current.checked = false;
    }

    useEffect(fetchUsers, []);

    return (
        <>
            <ExportDialog resource="users" id="export" open={exportOpen} setOpen={setExportOpen} entities={users} />
            <Toast content={toast} setContent={setToast} />
            <div className="space-y-8">
                <div>
                    <h2 className="text-2xl font-bold">Users</h2>
                </div>
                <div className="w-full flex items-center justify-between gap-4">
                    <div className="flex-1">
                        <div className="w-full max-w-sm rounded border border-zinc-500 bg-zinc-900/50 flex items-center gap-2 px-3 py-1 outline outline-transparent has-focus:outline-indigo-500 duration-150">
                            <i className="bi bi-search text-zinc-500"></i>
                            <input
                                type="text"
                                id="search"
                                className="flex-1 focus:outline-none placeholder:text-zinc-500"
                                placeholder="Search users..."
                                value={query}
                                onInput={(e) => setQuery(e.currentTarget.value)}
                            />
                            {query && (
                                <button aria-label="Clear search" onClick={() => setQuery("")}>
                                    <i className="bi bi-x-lg"></i>
                                </button>
                            )}
                        </div>
                    </div>
                    <div className="flex items-center gap-4">
                        <button
                            type="button"
                            aria-label="Refresh table"
                            onClick={fetchUsers}
                            className="rounded-full border border-zinc-500 disabled:bg-zinc-700"
                        >
                            <i className={`bi bi-arrow-clockwise text-lg p-2 ${loading ? "spin" : ""}`}></i>
                        </button>
                        <label
                            className="relative flex items-center gap-1 px-4 py-1 rounded border border-zinc-500 cursor-pointer"
                        >
                            <input type="checkbox" className="peer hidden" ref={checkboxRef} />
                            <span>Actions</span>
                            <i className="bi bi-caret-down-fill text-xs"></i>

                            <ul
                                className="absolute top-full right-0 min-w-40 w-max my-2 bg-zinc-800  border border-zinc-500 py-2 rounded invisible opacity-0  pointer-events-none peer-checked:visible peer-checked:opacity-100  peer-checked:pointer-events-auto  duration-300"
                            >
                                <li className="px-4 py-2 hover:bg-zinc-700 duration-150">
                                    <button
                                        type="button"
                                        onClick={(e) => { closeDropdown(e); setExportOpen(true); }}
                                        className="flex gap-2 items-center w-full"
                                    >
                                        <i className="bi bi-download"></i>
                                        Export
                                    </button>
                                </li>
                            </ul>
                        </label>
                        <Link
                            href="/hq/users/new"
                            className="flex items-center gap-1 px-4 py-1 rounded bg-indigo-500 border border-indigo-500 hover:bg-indigo-600 hover:border-indigo-600 duration-150"
                        >
                            New user
                        </Link>
                    </div>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full rounded-lg border border-neutral-500 border-separate border-spacing-0">
                        <thead>
                            <tr>
                                <th className="text-left font-bold border-b border-neutral-500 p-2">
                                    <div className="flex items-center gap-1">
                                        <span>ID</span>
                                        <button aria-label="Sort by ID" className="rounded-full hover:bg-zinc-700 duration-150">
                                            <i className="bi bi-arrow-down-up text-[10px] p-1"></i>
                                        </button>
                                    </div>
                                </th>
                                <th className="text-left font-bold border-b border-neutral-500 p-2">
                                    <div className="flex items-center gap-1">
                                        <span>Name</span>
                                        <button aria-label="Sort by name" className="rounded-full hover:bg-zinc-700 duration-150">
                                            <i className="bi bi-arrow-down-up text-[10px] p-1"></i>
                                        </button>
                                    </div>
                                </th>
                                <th className="text-left font-bold border-b border-neutral-500 p-2">
                                    <div className="flex items-center gap-1">
                                        <span>Email address</span>
                                        <button aria-label="Sort by email" className="rounded-full hover:bg-zinc-700 duration-150">
                                            <i className="bi bi-arrow-down-up text-[10px] p-1"></i>
                                        </button>
                                    </div>
                                </th>
                                <th className="text-left font-bold border-b border-neutral-500 p-2">
                                    <div className="flex items-center gap-1">
                                        <span>Role</span>
                                        <button aria-label="Sort by role" className="rounded-full hover:bg-zinc-700 duration-150">
                                            <i className="bi bi-arrow-down-up text-[10px] p-1"></i>
                                        </button>
                                    </div>
                                </th>
                                <th className="text-left font-bold border-b border-neutral-500 p-2">
                                    <div className="flex items-center gap-1">
                                        <span>Password</span>
                                    </div>
                                </th>
                                <th className="text-left font-bold border-b border-neutral-500 p-2">
                                    <div className="flex items-center gap-1">
                                        <span>Status</span>
                                        <button aria-label="Sort by status" className="rounded-full hover:bg-zinc-700 duration-150">
                                            <i className="bi bi-arrow-down-up text-[10px] p-1"></i>
                                        </button>
                                    </div>
                                </th>
                                <th className="text-left font-bold border-b border-neutral-500 p-2">
                                    <div className="flex items-center gap-1">
                                        <span>Permissions</span>
                                        <button aria-label="Sort by permission count" className="rounded-full hover:bg-zinc-700 duration-150">
                                            <i className="bi bi-arrow-down-up text-[10px] p-1"></i>
                                        </button>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {loading ? (
                                <tr>
                                    <td colSpan={9999}>
                                        <div className="w-full p-2 flex justify-center">
                                            <Spinner />
                                        </div>
                                    </td>
                                </tr>
                            ) : users.length ? users.map((user, i) => (
                                <tr key={i} className="group">
                                    <td className="p-2 group-not-last:border-b border-zinc-500">
                                        <Link href={`/hq/users/${user.id}`} className="line-clamp-1 text-xs opacity-60 hover:underline">
                                            {user.id}
                                        </Link>
                                    </td>
                                    <td className="p-2 group-not-last:border-b border-zinc-500">
                                        <div className="flex items-center gap-2">
                                            <img
                                                src={user.profilePictureUrl}
                                                alt={`${user.firstName}'s profile`}
                                                className="size-9 rounded-full object-center object-cover border border-zinc-500"
                                            />
                                            <span>{user.firstName} {user.lastName}</span>
                                        </div>
                                    </td>
                                    <td className="p-2 group-not-last:border-b border-zinc-500">
                                        <p className="max-w-xs truncate">
                                            {user.email}
                                        </p>
                                    </td>
                                    <td className="p-2 group-not-last:border-b border-zinc-500">
                                        <p className="max-w-xs truncate">
                                            {user.role}
                                        </p>
                                    </td>
                                    <td className="p-2 group-not-last:border-b border-zinc-500">
                                        {user.password ? (
                                            <span className="inline-flex gap-1 text-sm px-2 rounded-full border bg-green-950 text-green-400 border-green-500">
                                                <i className="bi bi-check"></i>
                                                Set
                                            </span>
                                        ) : (
                                            <span className="inline-flex gap-1 text-sm px-2 rounded-full border bg-red-950 text-red-400 border-red-500">
                                                <i className="bi bi-x"></i>
                                                Unset
                                            </span>
                                        )}
                                    </td>
                                    <td className="p-2 group-not-last:border-b border-zinc-500">
                                        <UserStatusBadge status={user.status} />
                                    </td>
                                    <td className="p-2 group-not-last:border-b border-zinc-500">
                                        {user.permissions.length}
                                    </td>
                                </tr>
                            )) : (
                                <tr>
                                    <td colSpan={9999}>
                                        <p className="w-full p-2 text-center opacity-60">
                                            No rows were found.
                                        </p>
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </>
    );
}

// src/routes/(protected)/users/+page.svelte
<script lang="ts">
    import { ColorScheme } from "$common/enum/ColorScheme";
    import { UserStatus } from "$common/enum/UserStatus";
    import Container from "$lib/Container.svelte";
    import type { PageProps } from "./$types";
    let search: string = $state("");

    const statusStyles: Record<UserStatus, string> = {
        [UserStatus.Unverified]: "text-yellow-700 border-yellow-700",
        [UserStatus.Pending]: "text-slate-700 border-slate-700",
        [UserStatus.Active]: "text-green-700 border-green-700",
        [UserStatus.Deleted]: "text-green-700 border-green-700",
    };

    const themeIcons: Record<ColorScheme, string> = {
        [ColorScheme.Light]: "bi-sun",
        [ColorScheme.Dark]: "bi-moon",
        [ColorScheme.System]: "bi-display",
    };

    let { data }: PageProps = $props();

</script>

<Container maxWidth="max-w-5xl" class="space-y-8 my-8" centered>
    <div class="flex items-center gap-4">
        <i class="bi bi-person-square text-4xl"></i>
        <div>
            <h2 class="font-semibold text-2xl">Admin Users</h2>
            <p class="opacity-60">
                Manage and view all registered admin users on the platform.
            </p>
        </div>
    </div>
    <div>
        <div class="space-y-4">
            <div
                class="group flex items-center p-2 gap-3 rounded border border-zinc-600 w-full max-w-sm has-focus:ring-2 ring-blue-500 duration-150"
            >
                <i class="bi bi-search text-lg opacity-60"></i>
                <input
                    type="text"
                    name="searchUsers"
                    id="searchUsers"
                    placeholder="Search users by name..."
                    class="min-w-0 flex-1 focus:outline-none"
                    bind:value={search}
                />
                {#if search}
                    <button
                        class="cursor-pointer"
                        aria-label="Clear search box"
                        onclick={() => (search = "")}
                    >
                        <i class="bi bi-x-lg"></i>
                    </button>
                {/if}
            </div>
            <div>
                <table class="w-full border-separate border-spacing-0 rounded-lg border border-zinc-600">
                    <thead>
                        <tr class="group first:border-b border-zinc-600 text-left *:p-2">
                            <th class="group-first:border-b border-zinc-600">ID</th>
                            <th class="group-first:border-b border-zinc-600">User</th>
                            <th class="group-first:border-b border-zinc-600">Email</th>
                            <th class="group-first:border-b border-zinc-600">Password</th>
                            <th class="group-first:border-b border-zinc-600">Status</th>
                            <th class="group-first:border-b border-zinc-600">Theme</th>
                            <th class="group-first:border-b border-zinc-600"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {#each data.rows as user}
                            <tr class="group not-last:border-b border-zinc-600 *:not-last:p-2 hover:bg-zinc-700 duration-150">
                                <td class="group-not-last:border-b border-zinc-600">
                                    <span class="text-xs opacity-60 line-clamp-1">
                                        UUID:{user.id.split("-").at(-1)}
                                    </span>
                                </td>
                                <td class="group-not-last:border-b border-zinc-600">
                                    <div class="w-full flex gap-2 items-center">
                                        <figure class="size-8 rounded-full bg-zinc-700 overflow-hidden">
                                            <img src={user.pfpSrc} alt="{user.name}'s profile" class="object-cover object-center"/>
                                        </figure>
                                        <span class="font-semibold line-clamp-1">
                                            {user.name}
                                        </span>
                                    </div>
                                </td>
                                <td class="group-not-last:border-b border-zinc-600">
                                    <span class="opacity-60 line-clamp-1">{user.email}</span>
                                </td>
                                <td class="group-not-last:border-b border-zinc-600">
                                    <span class="rounded-full px-2 py-1 text-xs border font-semibold {user.password
                                        ? 'border-sky-700 text-sky-700'
                                        : 'border-slate-700 text-slate-700'}"
                                    >
                                        {user.password ? "set" : "unset"}
                                    </span>
                                </td>
                                <td class="group-not-last:border-b border-zinc-600">
                                    <span class="rounded-full px-2 py-1 text-xs border font-semibold {statusStyles[user. status]}">
                                        {user.status}
                                    </span>
                                </td>
                                <td class="group-not-last:border-b border-zinc-600">
                                    <div class="flex items-center gap-2 opacity-60">
                                        <i class="bi {themeIcons[user.theme]} text-sm"></i>
                                        <span>{user.theme}</span>
                                    </div>
                                </td>
                                <td class="">
                                    <div class="relative group">
                                        <label class="flex w-fit p-1 rounded cursor-pointer hover:bg-zinc-800/75 duration-150">
                                            <i class="bi bi-three-dots-vertical"></i>
                                            <input id="showOptions" type="checkbox" class="hidden">
                                        </label>
                                        <div class="hidden group-has-checked:block absolute right-0 -translate-x-4 -ml-4 z-5 w-max max-w-50 *:first:pt-2 *:last:pb-2 bg-zinc-800 space-y-2 border border-zinc-600 rounded shadow-md">
                                            <h4 class="px-4 font-semibold">Actions</h4>
                                            <hr class="border-zinc-600">
                                            <ul class="*:py-2 *:px-4 border-zinc-600">
                                                <li class="hover:bg-zinc-700 duration-150 cursor-pointer">
                                                    <a href="/users/{user.id}">View details</a>
                                                </li>
                                                <li class="hover:bg-zinc-700 duration-150 text-red-700 cursor-pointer">
                                                    <span>Delete user</span>
                                                </li> <!-- @todo implement -->
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {/each}
                    </tbody>
                </table>
            </div>
            <div class="flex items-center justify-between">
                <div>
                    <span class="opacity-60"> Showing 1-10 of 30 </span>
                </div>
                <div class="flex items-center gap-4">
                    <button
                        type="button"
                        class="rounded border border-zinc-600 flex items-center gap-2 p-2 hover:bg-zinc-700 duration-150 cursor-pointer"
                    >
                        <i class="bi bi-chevron-left text-xs"></i>
                        <span>Previous</span>
                    </button>
                    <button
                        type="button"
                        class="rounded border border-zinc-600 flex items-center gap-2 p-2 hover:bg-zinc-700 duration-150 cursor-pointer"
                    >
                        <span>Next</span>
                        <i class="bi bi-chevron-right text-xs"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</Container>
