// src/routes/(protected)/users/new/+page.svelte
<script lang="ts">
    import Container from "$lib/Container.svelte";
    import Tooltip from "$lib/Tooltip.svelte";

    const ACTION = "action";
    const ENTITY = "entity";

    let action: string = $state(ACTION);
    let entity: string = $state(ENTITY);

    let permissions: Set<string> = $state(new Set());

    const addPermission = () => {
        if (action !== ACTION && entity !== ENTITY) {
            permissions = new Set(permissions).add(`${action}:${entity}`);
            action = ACTION;
            entity = ENTITY;
        }
    };

    const removePermission = (permission: string) => {
        if (permissions.has(permission)) {
            permissions = new Set([...permissions].filter(p => p !== permission));
        }
    };

    let permissionString: string = $derived(
        JSON.stringify([...permissions]),
    );

    $effect(() => console.log(action));
    $effect(() => console.log(entity));
    $effect(() => permissions.forEach((p) => console.log(p)));
</script>

<Container
    id="new-user"
    maxWidth="max-w-xl"
    class="space-y-8 my-8"
    centered
>
    <div class="flex items-center gap-4">
        <i class="bi bi-person-square text-4xl"></i>
        <div>
            <h2 class="font-semibold text-2xl">Invite user</h2>
            <p class="opacity-60">
                Send an invitation to add a new user to this organization
            </p>
        </div>
    </div>
    <form
        method="POST"
        class="rounded-lg bg-zinc-700/20 border border-zinc-600 p-4 space-y-6"
    >
        <div>
            <h3 class="text-lg font-semibold">User information</h3>
            <p class="text-sm opacity-60">
                Enter the details of the person you want to invite
            </p>
        </div>
        <div class="space-y-6">
            <div class="space-y-2">
                <label
                    for="firstName"
                    class="block font-semibold opacity-80 text-sm"
                    >First name</label
                >
                <div
                    class="group flex items-center gap-2 p-2 rounded border border-zinc-600 has-focus:ring-2 ring-blue-500 duration-150"
                >
                    <i class="bi bi-person text-lg opacity-60"></i>
                    <input
                        type="text"
                        name="firstName"
                        id="firstName"
                        placeholder="John"
                        class="flex-1 min-w-0 focus:outline-none"
                    />
                </div>
            </div>
            <div class="space-y-2">
                <label
                    for="lastName"
                    class="block font-semibold opacity-80 text-sm"
                    >Last name</label
                >
                <div
                    class="group flex items-center gap-2 p-2 rounded border border-zinc-600 has-focus:ring-2 ring-blue-500 duration-150"
                >
                    <i class="bi bi-person text-lg opacity-60"></i>
                    <input
                        type="text"
                        name="lastName"
                        id="lastName"
                        placeholder="Doe"
                        class="flex-1 min-w-0 focus:outline-none"
                    />
                </div>
            </div>
            <div class="space-y-2">
                <label
                    for="email"
                    class="block font-semibold opacity-80 text-sm"
                    >Email address</label
                >
                <div
                    class="group flex items-center gap-2 p-2 rounded border border-zinc-600 has-focus:ring-2 ring-blue-500 duration-150"
                >
                    <i class="bi bi-envelope text-lg opacity-60"></i>
                    <input
                        type="email"
                        name="email"
                        id="email"
                        placeholder="name@example.com"
                        class="flex-1 min-w-0 focus:outline-none"
                    />
                </div>
            </div>
            <div class="space-y-2">
                <div class="flex items-center gap-1">
                    <span class="block font-semibold opacity-80 text-sm">Permissions</span>
                    <Tooltip>
                        <p class="text-sm">
                            Roles will only be assigned upon approval, after the
                            user has confirmed their email and created a
                            password.
                        </p>
                    </Tooltip>
                </div>
                <input
                    type="text"
                    name="permissions"
                    id="permissions"
                    class="hidden"
                    bind:value={permissionString}
                />
                <div class="flex items-center gap-4">
                    <div class="flex-1 flex items-center gap-1">
                        <select
                            bind:value={action}
                            class="flex-1 appearance-base-select picker:appearance-base-select picker:my-1 picker:border picker:border-zinc-600 picker:rounded border border-zinc-600 has-focus:ring-2 ring-blue-500 rounded p-2 picker-icon:scale-x-80 picker-icon:scale-y-60 picker-icon:opacity-40 open:picker-icon:rotate-180 picker-icon:duration-300 cursor-pointer"
                        >
                            <button type="button">
                                <selectedcontent class="flex items-center gap-2"></selectedcontent>
                            </button>
                            <option
                                value="create"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-plus-lg"></i>
                                <span>create</span>
                            </option>
                            <option
                                value="list"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-view-list"></i>
                                <span>list</span>
                            </option>
                            <option
                                value="update"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-pencil"></i>
                                <span>update</span>
                            </option>
                            <option
                                value="delete"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-trash"></i>
                                <span>delete</span>
                            </option>
                        </select>
                        <span class="text-lg font-bold">:</span>
                        <select
                            bind:value={entity}
                            class="flex-1 appearance-base-select picker:appearance-base-select picker:my-1 picker:border picker:border-zinc-600 picker:rounded border border-zinc-600 has-focus:ring-2 ring-blue-500 rounded p-2 picker-icon:scale-x-80 picker-icon:scale-y-60 picker-icon:opacity-40 open:picker-icon:rotate-180 picker-icon:duration-300 cursor-pointer"
                        >
                            <button type="button">
                                <selectedcontent class="flex items-center gap-2"></selectedcontent>
                            </button>
                            <option
                                value="user"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-person-circle"></i>
                                <span>user</span>
                            </option>
                            <option
                                value="project"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-folder"></i>
                                <span>project</span>
                            </option>
                            <option
                                value="member"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-person-vcard"></i>
                                <span>member</span>
                            </option>
                            <option
                                value="message"
                                class="flex items-center gap-2 px-4 py-2 hover:bg-zinc-700 duration-150 checkmark:hidden"
                            >
                                <i class="bi bi-envelope"></i>
                                <span>message</span>
                            </option>
                        </select>
                    </div>
                    <button
                        type="button"
                        onclick={addPermission}
                        class="bg-blue-500 rounded p-2 hover:bg-blue-600 active:bg-blue-500 duration-150 cursor-pointer"
                        aria-label="Add permission to list"
                    >
                        Add
                    </button>
                </div>
            </div>
            <div class="space-y-2">
                <span class="block font-semibold opacity-80 text-sm"
                    >Permission list</span
                >
                {#if permissions.size}
                    <ul class="w-full border border-zinc-700 rounded">
                        {#each permissions as perm}
                        <li class="flex w-full p-2 not-last:border-b border-zinc-700">
                            <span class="flex-1">{perm}</span>
                            <button
                                type="button"
                                class="cursor-pointer text-xs hover:underline text-red-700"
                                onclick={() => removePermission(perm)}
                            >Remove</button>
                        </li>
                        {/each}
                    </ul>
                {:else}
                    <p class="text-center opacity-60 text-sm">
                        No permissions added
                    </p>
                {/if}
            </div>
            <div>
                <input
                    type="submit"
                    value="Invite user"
                    class="w-full text-center p-2 bg-blue-500 rounded hover:bg-blue-600 active:bg-blue-500 duration-150 cursor-pointer"
                />
            </div>
        </div>
    </form>
</Container>

// src/app/(admin)/hq/users/new/page.tsx
"use client";

import { PermissionAction } from "@/common/enum/PermissionAction";
import { PermissionEntity } from "@/common/enum/PermissionEntity";
import Toggle from "@/components/Toggle";
import { SyntheticEvent, useEffect, useState, type JSX } from "react";

export default function NewUserView(): JSX.Element {
    const [firstName, setFirstName] = useState("");
    const [lastName, setLastName] = useState("");
    const [email, setEmail] = useState("");
    const [role, setRole] = useState("");
    const [entity, setEntity] = useState(PermissionEntity.NONE);
    const [action, setAction] = useState(PermissionAction.NONE);
    const [permissions, setPermissons] = useState(new Set<string>());
    const [permissionText, setPermissonText] = useState("");
    const [showOnPage, setShowOnPage] = useState(false);

    const addPermission = () => {
        if (!action || !entity) return;

        setPermissons(p => new Set([...p, `${action}:${entity}`]));

        setAction(PermissionAction.NONE);
        setEntity(PermissionEntity.NONE);
    };

    const removePermission = (value: string) => {
        setPermissons(p => new Set([...p].filter(i => i !== value)));
    }

    const resetForm = (event: SyntheticEvent<HTMLFormElement>) => {
        event.preventDefault();
        setFirstName("");
        setLastName("");
        setEmail("");
        setRole("");
        setEntity(PermissionEntity.NONE);
        setAction(PermissionAction.NONE);
        setPermissons(new Set());
        setShowOnPage(false);
    }

    useEffect(() => setPermissonText(JSON.stringify(Array.from(permissions))), [permissions]);

    useEffect(() => console.log({ useOTP: showOnPage }), [showOnPage]);

    return (
        <div className="flex flex-col gap-8">
            <div>
                <h2 className="text-2xl font-bold">New User</h2>
                <p className="opacity-60">
                    Configure profile details and
                    platform permissions for a new team member.
                </p>
            </div>
            <form action="/api/hq/users" method="POST" className="contents" onReset={resetForm}>
                <fieldset className="p-6 border border-zinc-500 space-y-4 bg-zinc-700">
                    <h3 className="text-xl font-semibold flex items-center gap-2">
                        <i className="bi bi-person-vcard"></i>
                        Identity
                    </h3>
                    <hr className="opacity-20" />
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-1">
                            <label htmlFor="firstName" className="block text-sm opacity-60 uppercase font-semibold">First name</label>
                            <div className="flex items-center border border-zinc-600 rounded bg-zinc-800/60 outline outline-transparent has-focus:outline-indigo-500 duration-150 px-2 py-1 gap-2">
                                <input
                                    type="text"
                                    name="firstName"
                                    id="firstName"
                                    placeholder="John"
                                    className="flex-1 focus:outline-none text-lg"
                                    value={firstName}
                                    onInput={(e) => setFirstName(e.currentTarget.value)}
                                />
                            </div>
                        </div>
                        <div className="space-y-1">
                            <label htmlFor="lastName" className="block text-sm opacity-60 uppercase font-semibold">Last name</label>
                            <div className="flex items-center border border-zinc-600 rounded bg-zinc-800/60 outline outline-transparent has-focus:outline-indigo-500 duration-150 px-2 py-1 gap-2">
                                <input
                                    type="text"
                                    name="lastName"
                                    id="lastName"
                                    placeholder="Doe"
                                    className="flex-1 focus:outline-none text-lg"
                                    value={lastName}
                                    onInput={(e) => setLastName(e.currentTarget.value)}
                                />
                            </div>
                        </div>
                        <div className="space-y-1">
                            <label htmlFor="email" className="block text-sm opacity-60 uppercase font-semibold">Email address</label>
                            <div className="flex items-center border border-zinc-600 rounded bg-zinc-800/60 outline outline-transparent has-focus:outline-indigo-500 duration-150 px-2 py-1 gap-2">
                                <input
                                    type="email"
                                    name="email"
                                    id="email"
                                    placeholder="name@example.com"
                                    className="flex-1 focus:outline-none text-lg"
                                    value={email}
                                    onInput={(e) => setEmail(e.currentTarget.value)}
                                />
                            </div>
                        </div>
                        <div className="space-y-1">
                            <label htmlFor="role" className="block text-sm opacity-60 uppercase font-semibold">Role</label>
                            <div className="flex items-center border border-zinc-600 rounded bg-zinc-800/60 outline outline-transparent has-focus:outline-indigo-500 duration-150 px-2 py-1 gap-2">
                                <input
                                    type="tel"
                                    name="role"
                                    id="role"
                                    placeholder="Art Director"
                                    className="flex-1 focus:outline-none text-lg"
                                    value={role}
                                    onInput={(e) => setRole(e.currentTarget.value)}
                                />
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div className="flex gap-8">
                    <fieldset className="flex-3 p-6 border border-zinc-500 space-y-4 bg-zinc-700">
                        <h3 className="text-xl font-semibold flex items-center gap-2">
                            <i className="bi bi-key"></i>
                            Access Management
                        </h3>
                        <hr className="opacity-20" />
                        <p className="opacity-60">Select permissions for this user to have across the platform.</p>
                        <div className="w-full flex items-stretch gap-4">
                            <div className="w-full flex items-center gap-2">
                                <select
                                    id="action"
                                    className="custom-select flex-1"
                                    value={action}
                                    onChange={(e) => setAction(e.target.value as PermissionAction)}
                                >
                                    {Object.entries(PermissionAction).map(([key, value]) =>
                                        value ? (
                                            <option key={key} value={key}>{value}</option>
                                        ) : (
                                            <option key={key} value={value} disabled hidden />
                                        )
                                    )}
                                </select>
                                <span>:</span>
                                <select
                                    id="entity"
                                    className="custom-select flex-1"
                                    value={entity}
                                    onChange={(e) => setEntity(e.target.value as PermissionEntity)}
                                >
                                    {Object.entries(PermissionEntity).map(([key, value]) =>
                                        value ? (
                                            <option key={key} value={key}>{value}</option>
                                        ) : (
                                            <option key={key} value={value} disabled hidden />

                                        )
                                    )}
                                </select>
                            </div>
                            <button
                                type="button"
                                className="bg-indigo-500 hover:bg-indigo-600 duration-150 rounded text-white px-2"
                                onClick={addPermission}
                            >
                                Add
                            </button>
                        </div>
                        <div>
                            <h4 className="text-lg font-semibold">Permissions</h4>
                            {permissions.size ? (
                                <ul className="py-4 w-full">
                                    {Array.from(permissions).map((p, i) => (
                                        <li key={i} className="flex p-2 rounded hover:bg-zinc-600 duration-150">
                                            <p className="flex-1">{p}</p>
                                            <button onClick={() => removePermission(p)}>
                                                <i className="bi bi-x-lg"></i>
                                            </button>
                                        </li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="opacity-60"><em>No permissions added.</em></p>
                            )}
                        </div>
                    </fieldset>
                    <fieldset className="flex-2 p-6 border border-zinc-500 space-y-4 bg-zinc-700">
                        <h3 className=" text-xl font-semibold flex items-center gap-2">
                            <i className="bi bi-globe-americas"></i>
                            Landing Page
                        </h3>
                        <hr className="opacity-20" />
                        <div className="space-y-1">
                            <Toggle id="useOTP" state={showOnPage} setState={setShowOnPage} label="Show on Team section" labelPosition="left" />
                            <p className="opacity-60">
                                Show this user's information on TypeCrafter's HQ landing page.
                            </p>
                        </div>
                    </fieldset>
                    <input type="text" name="permissions" id="permisions" value={permissionText} className="hidden" readOnly />
                </div>
                <div className="w-full flex justify-end items-center gap-4">
                    <input
                        type="reset" 
                        value="Cancel" 
                        className="bg-zinc-500 px-3 py-2 rounded hover:bg-zinc-600 duration-150" 
                    />
                    <input type="submit" value="Create User" className="bg-indigo-500 px-3 py-2 rounded hover:bg-indigo-600 duration-150" />
                </div>
            </form>
        </div>
    );
}
