// src/lib/UserProfile.svelte
<script lang="ts">
    interface UserProfileProps {
        profilePictureUrl: string;
        firstName: string;
        lastName: string;
        email: string;
    }

    const { profilePictureUrl, firstName, lastName, email }: UserProfileProps = $props();
</script>

<a href="/users/me" class="w-full">
    <figure class="w-full flex p-4 gap-4 items-center hover:bg-zinc-700 duration-200 rounded-lg">
        <div class="size-16 rounded-full overflow-hidden">
            <img src={profilePictureUrl} alt={`${firstName} ${lastName}'s profile`} class="object-cover object-center">
        </div>
        <figcaption class="flex-1">
            <h2 class="text-xl font-semibold line-clamp-1">{firstName} {lastName}</h2>
            <p class="opacity-60 line-clamp-1">{email}</p>
        </figcaption>
    </figure>
</a>

// src/components/UserProfile.tsx
import Image from "next/image";
import Link from "next/link";
import type { JSX } from "react";

export interface UserProfileProps {
    firstName: string;
    lastName: string;
    profilePictureUrl?: string;
    role: string;
}

export default function UserProfile({
    firstName,
    lastName,
    profilePictureUrl,
    role
}: UserProfileProps): JSX.Element {
    return (
        <Link href="/users/profile" className="inline-flex items-center gap-4 rounded hover:bg-zinc-700 duration-150 py-1 px-2">
            <div className="flex justify-center items-center size-10 rounded-full overflow-hidden bg-blue-500/20 border-2 border-blue-500 text-blue-500">
                {profilePictureUrl ? (
                    <Image src={profilePictureUrl} alt={`${firstName} ${lastName}'s profile`}/>
                ) : (
                    <span className="font-semibold">{firstName.at(0)}{lastName.at(0)}</span>
                )}
            </div>
            <div>
                <h2 className="font-semibold">{firstName} {lastName}</h2>
                <p className="text-xs opacity-60">{role}</p>
            </div>
        </Link>
    );
}
